#Gather facts using setup module.
#
---
 - name: Gather facts
   hosts: all
   become: yes
   tasks:
     - name: Gather facts using setup module
       setup:
         gather_subset: hardware,virtual

