---
- name: My test playbook
  hosts: webservers
  become : true
  tasks: 
    - name: Install a httpd package
      yum: 
       name: httpd
       state: installed
    - name: start a httpd service
      service:
        name: httpd
        state: started
    - name: Check the status of service
      command:
        cmd: systemctl status httpd
        register: httpd_status
        ignore_errors: yes                #in case service is not running
        changed_when: false               #read-only check

