---
 - name: My Test Playbook
   hosts: webservers
   become: true
   tasks:
     - name: Stop the httpd package
       service: 
          name: httpd
          state: stopped
     - name: Uninstall the httpd package
       yum:
         name: httpd*
         state: removed

     - name: Status of httpd package
       yum:
         name: httpd
         state: status

